export { isXs } from './isXs'
export { isMobile } from './isMobile'
export { requestTimeout, clearRequestTimeout } from './requestTimeout'
export { getCookie } from './getCookie'
export { getPhoneData } from './getPhoneData'
export { map } from './map'
export { clamp } from './clamp'
export { default as toggleFullscreen } from './toggleFullscreen'
