export { isXs } from './isXs'
export { isMobile } from './isMobile'
export { getCookie } from './getCookie'
export { getPhoneData } from './getPhoneData'
export { default as toggleFullscreen } from './toggleFullscreen'
