export default {
  SET_APP_LOADED: "SET_APP_LOADED",
  SET_CURRENT_STEP: "SET_CURRENT_STEP",
  SET_CURRENT_SCENE: "SET_CURRENT_SCENE",
  SET_SPLIT_SCREEN: "SET_SPLIT_SCREEN",
  SET_USER_CURRENT_SCENE: "SET_USER_CURRENT_SCENE",
  SET_USER_INDICATION_ACTIVE: "SET_USER_INDICATION_ACTIVE",
  SET_USER_INDICATION_OPEN: "SET_USER_INDICATION_OPEN",
  SET_USER_INDICATION_TITLE: "SET_USER_INDICATION_TITLE",
  SET_USER_INDICATION_DESCRIPTION: "SET_USER_INDICATION_DESCRIPTION",
}
