export default {
  SET_APP_LOADED: "SET_APP_LOADED",
  SET_CURRENT_STEP: "SET_CURRENT_STEP",
  SET_CURRENT_SCENE: "SET_CURRENT_SCENE",
  SET_SPLIT_SCREEN: "SET_SPLIT_SCREEN",
  SET_USER_CURRENT_SCENE: "SET_USER_CURRENT_SCENE",
}
